
// PLAYER CONSTANTS

export const ADD_FAVOURITE_PLAYER = 'ADD_FAVOURITE_PLAYER';
export const REMOVE_FAVOURITE_PLAYER = 'REMOVE_FAVOURITE_PLAYER';


// PRODUCT CONSTANTS
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const CART_EMPTY = 'CART_EMPTY';



// ADDRESS CONSTANTS

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';


// PAYMENT CONSTANTS


export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";

